export enum UserAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE_SALES_REPORT = 'CREATE_SALES_REPORT',
  UPDATE_SALES_REPORT = 'UPDATE_SALES_REPORT',
  CREATE_PURCHASE_REPORT = 'CREATE_PURCHASE_REPORT',
  UPDATE_PURCHASE_REPORT = 'UPDATE_PURCHASE_REPORT',
  UPLOAD_FILE = 'UPLOAD_FILE',
  DOWNLOAD_FILE = 'DOWNLOAD_FILE',
  EXPORT_DATA = 'EXPORT_DATA',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
}